language: python

python:
  - "2.7"
  
before_script:
  - /bin/bash ./.travis.sh
  
install:
  - "pip install ."
  - "pip install requests"
  - "pip install python-coveralls"
  - "pip install coverage"
  - "pip install nose"

script:
  - nosetests -w /tests --with-coverage
after_success: coveralls
