language: python

python:
  - "2.7"
  
before_script:
  - /bin/bash ./.travis.sh
  
install:
  - "pip install ."
  - "pip install requests"
  - "pip install pytest pytest-cov"
  - "pip install coveralls"

script:
  - py.test
after_success: coveralls
